root: ./

​structure:  
    readme: README.md

redirects:
    umbraco-cms/fundamentals/setup/upgrading/general: umbraco-cms/fundamentals/setup/upgrading/README.md
    v/workflow: umbraco-workflow/README.md
    set-up/2-factor-authentication-on-cloud: /set-up/Multi-factor-authentication-on-cloud.md
