root: ./

​structure:  
    readme: README.md
    summary: SUMMARY.md

redirects:
    umbraco-workflow/configuration: umbraco-workflow/getting-started/configuration.md
    umbraco-workflow/dashboards-and-buttons: umbraco-workflow/getting-started/dashboards-and-buttons.md
    umbraco-workflow/notifications: umbraco-workflow/getting-started/notifications.md
    umbraco-workflow/workflow-content-app: umbraco-workflow/getting-started/workflow-content-app.md