---
extends: substitution
message: "Prefer %s over '%s.'"
level: warning
ignorecase: true
swap:
  blacklist: "'deny list'"
  whitelist: "'allow list'"
  black list: "'deny list'"
  white list: "'allow list'"  
  master: "'primary'"
  slave: "'secondary'"
  e.g.: "'for instance'"
  eg.: "'for instance'"
  etc.: "'and so on'"
