root: ./

​structure:  
    readme: README.md
    summary: SUMMARY.md

redirects:
    fundamentals/setup/install/running-umbraco-on-a-mac: fundamentals/setup/install/running-umbraco-on-linux-macos.md
    umbraco-cms/v/13.latest-rc/fundamentals/backoffice/requirements: umbraco-cms/fundamentals/setup/requirements.md

